[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.7", features = ["cargo"]}
sfml = "0.18.1"
rand = "0.8.5"
bitvec = "1.0.1"